version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: cinema_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cinema}
      POSTGRES_USER: ${POSTGRES_USER:-cinema}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cinema}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DEBUG: "1"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-dev-secret}
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${POSTGRES_DB:-cinema}
      DB_USER: ${POSTGRES_USER:-cinema}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-cinema}
      DB_HOST: db
      DB_PORT: "5432"
      ALLOWED_HOSTS: "*"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  db_data: